# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0004_auto_20160414_0005'),
        ('imager_images', '0006_remove_album_cover'),
    ]

    operations = [
    ]
