# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0005_album_cover'),
        ('imager_images', '0007_merge'),
    ]

    operations = [
    ]
